### PR TITLE
Updated Invalid Audio Path Message and Updates Spaces in Audio File

### LINKED ISSUE #15: Bug: Spaces in audio file names
If given an audio file with spaces in its name, the audio file name shouldn’t be considered not valid because of the spaces. After this, replace all spaces with underscores. Also, remove leading and trailing whitespace in destination path and input audio file name.

### PR DESCRIPTION
**Pull request by moonsdust**
In this PR, the following changes were made:
- Trailing and leading whitespace is removed from `audio_name` and `input_audio_path`. 
- Updated invalid audio path message to `Invalid file format or input file could not be found. Please try again` in order to also indicate that the input audio file path may not exist.
- Replaced all spaces in `audio_name` to `_` so that the output CSV file does not contain any spaces.

### CODE REVIEW

**Review by carmen-chau — CHANGES_REQUESTED** [review]
@moonsdust 
Hey Emily, great work on this PR! 
2 minor changes I made. 
a) Had to strip whitespace from dest path 
b) I had to bug fix the generation of the final value of variable `input_audio_path`. 

Would appreciate you testing that out and making sure it also works on your end. 

Also, for reference, I added an additional print statement that shows users what the final destination path would be (after space replacement, truncating leading spaces, etc).

It is currently formatted as: `For reference, this is the output path:  #Insert path here#`. If you have any ideas on improving this print statement, feel free to modify the code

**Comment by moonsdust** [comment]
> @moonsdust Hey Emily, great work on this PR! 2 minor changes I made. a) Had to strip whitespace from dest path b) I had to bug fix the generation of the final value of variable `input_audio_path`.
> 
> Would appreciate you testing that out and making sure it also works on your end.
> 
> Also, for reference, I added an additional print statement that shows users what the final destination path would be (after space replacement, truncating leading spaces, etc).
> 
> It is currently formatted as: `For reference, this is the output path: #Insert path here#`. If you have any ideas on improving this print statement, feel free to modify the code

@carmen-chau Thanks for making the changes! I will be adding in additional changes soon

**Comment by moonsdust** [comment]
I tested it out and it works on my end! I also updated the output file path print statement.

**Comment by carmen-chau** [comment]
> I tested it out and it works on my end! I also updated the output file path print statement.

@moonsdust Thanks! I'll test and merge this tomorrow

**Pull request merged**
